name: Workflow Command
on: [push]

jobs:
    testing-workflow-commands:
        runs-on: ubuntu-latest
        steps:
            -   name: Setting an error message
                run: echo "::error::Missing semicolon"
            -   name: Setting an error message with params
                run: echo "::error title=Error Title, file=app.js,line=3,endLine=5,col=5,endColumn=7::Missing semicolon" 